dist: focal
sudo: false
latex: false
language: r
r: release
cache:
    packages: true
r_packages:
    - rsconnect
    - shiny
    - leaflet
    - RColorBrewer
    - ggplot2
script:
    - R -f deploy.R
